application: tabmemfree
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "7d"

handlers:
- url: /.*
	static_dir: public

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.iml
- ^(.*/)?.*/.idea/.*
